# Generated by Django 5.2 on 2025-04-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_premium_customuser_ui_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('learning_reminders', models.BooleanField(default=True)),
                ('weekly_progress', models.BooleanField(default=True)),
                ('new_features', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
