# Generated by Django 5.2 on 2025-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ui_language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
