# Generated by Django 5.2 on 2025-05-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_ui_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foreign_language',
            field=models.CharField(default='ua', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_language',
            field=models.CharField(default='de', max_length=50),
        ),
    ]
