# Generated by Django 5.2 on 2025-04-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('ua', models.CharField(max_length=255)),
                ('ar', models.CharField(max_length=255)),
                ('fa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('ua', models.CharField(max_length=255)),
                ('ar', models.CharField(max_length=255)),
                ('fa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.TextField()),
                ('ru', models.TextField()),
                ('ua', models.TextField()),
                ('ar', models.TextField()),
                ('fa', models.TextField()),
                ('image_2d', models.ImageField(blank=True, null=True, upload_to='phrases/2d/')),
                ('image_3d', models.ImageField(blank=True, null=True, upload_to='phrases/3d/')),
                ('is_shared', models.BooleanField(default=False)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='learn.subtopic')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='learn.topic'),
        ),
    ]
