# Generated by Django 5.2 on 2025-04-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='subtopics/2d/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='subtopics/3d/'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='topics/2d/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='topics/3d/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
    ]
