# Generated by Django 5.2 on 2025-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_phrase_owner_subtopic_image_2d_subtopic_image_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='audio_ar',
            field=models.FileField(blank=True, null=True, upload_to='audio/ar/'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='audio_de',
            field=models.FileField(blank=True, null=True, upload_to='audio/de/'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='audio_fa',
            field=models.FileField(blank=True, null=True, upload_to='audio/fa/'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='audio_ru',
            field=models.FileField(blank=True, null=True, upload_to='audio/ru/'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='audio_ua',
            field=models.FileField(blank=True, null=True, upload_to='audio/ua/'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='images/2d/'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='images/3d/'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='images/2d/'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='images/3d/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='images/2d/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='images/3d/'),
        ),
    ]
