# Generated by Django 5.2 on 2025-04-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_phrase_audio_ar_phrase_audio_de_phrase_audio_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='learn.topic'),
        ),
    ]
