# Generated by Django 5.2 on 2025-04-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_phrase_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='learn.topic'),
        ),
    ]
