# Generated by Django 5.2 on 2025-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_phrase_contentid_subtopic_contentid_topic_contentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
