# Generated by Django 5.2 on 2025-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_phrase_ar_alter_phrase_de_alter_phrase_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
