# Generated by Django 5.2 on 2025-05-01 09:34

import learn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_phrase_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image2d_upload_path),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image3d_upload_path),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image2d_upload_path),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image3d_upload_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image2d_upload_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to=learn.models.image3d_upload_path),
        ),
    ]
